import libs = cpp-httplib%lib{cpp-httplib}
import libs += gtest%lib{gtest}

exe{cpp-httplib-tests}: test/{hxx ixx txx cxx}{**} $libs

# Disable upstream failing tests
exe{cpp-httplib-tests}: test.options = "--gtest_filter=-\
*ChunkedEncodingTest*:\
BaseAuthTest.NoSSL:\
RedirectTest.HTTPBinNoSSLBasic:\
ServerTest.HeadMethod200Static:\
ServerTest.GetMethodDir:\
ServerTest.GetMethodDirTest:\
ServerTest.GetMethodDirTestWithDoubleDots:\
ServerTest.GetMethodDirMountTest:\
ServerTest.GetMethodDirMountTestWithDoubleDots:\
ServerTest.UserDefinedMIMETypeMapping:\
ServerTest.StaticFileRange:\
MountTest.Unmount:\
ProxyTest.NoSSLBasic:\
ClientProblemDetectionTest.ContentProvider"
