int_libs = # interface dependencies.
imp_libs = # implementation dependencies.

# since cpp-httplib is a header only lib all deps actually become
# interface dependencies
#
import int_libs += libcrypto%lib{crypto}
import int_libs += libssl%lib{ssl}
import int_libs += libz%lib{z}

lib{httplib}: {hxx ixx txx}{** -version} hxx{version} $imp_libs $int_libs

# include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-DCPPHTTPLIB_OPENSSL_SUPPORT" "-DCPPHTTPLIB_ZLIB_SUPPORT"

# export options.
#
lib{httplib}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-DCPPHTTPLIB_OPENSSL_SUPPORT" "-DCPPHTTPLIB_ZLIB_SUPPORT"
  cxx.export.libs = $int_libs
}

# install into the httplib/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/httplib/
  install.subdirs = true
}
