import intf_libs  = libbrotli%lib{brotli}
import intf_libs += openssl%lib{openssl} # @@ Bogus!
import intf_libs += libz%lib{z}

lib{cpp-httplib}: hxx{httplib} $intf_libs

# Build options.
#
cxx.poptions =+ "-I$src_base"

# Export options.
#
lib{cpp-httplib}:
{
  cxx.export.poptions = "-I$src_base"
  cxx.export.libs = $intf_libs
}

# Install directly into, say, /usr/include/, since it's one header 
# named after the library.
#
hxx{httplib}: install = include/
