import intf_libs += libbrotli%lib{brotlienc}
import intf_libs += libbrotli%lib{brotlidec}
import intf_libs += libssl%lib{ssl}
import intf_libs += libcrypto%lib{crypto}
import intf_libs += libz%lib{z}

lib{cpp-httplib}: hxx{httplib} $intf_libs

# Build options.
#
cxx.poptions =+ "-I$src_base" "-DCPPHTTPLIB_OPENSSL_SUPPORT" "-DCPPHTTPLIB_ZLIB_SUPPORT" "-DCPPHTTPLIB_BROTLI_SUPPORT"

# Export options.
#
lib{cpp-httplib}:
{
  cxx.export.poptions = "-I$src_base" "-DCPPHTTPLIB_OPENSSL_SUPPORT" "-DCPPHTTPLIB_ZLIB_SUPPORT" "-DCPPHTTPLIB_BROTLI_SUPPORT"
  cxx.export.libs = $intf_libs
}

# Install directly into, say, /usr/include/, since it's one header 
# named after the library.
#
hxx{*}: install = include/
